# Generated by Django 4.2.1 on 2023-07-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapa', models.CharField(max_length=255, unique=True)),
                ('marca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=255)),
                ('cantidad_viajes', models.IntegerField()),
                ('evaluacion_mensual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=255)),
                ('pasword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carga_transportada', models.IntegerField()),
                ('km_recorrido', models.IntegerField()),
                ('dia_semana', models.DateTimeField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransporteApp.camion')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransporteApp.chofer')),
            ],
        ),
        migrations.CreateModel(
            name='ViajeInterprovincial',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provincias_recorridas', models.IntegerField()),
                ('dia_regreso', models.DateTimeField()),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TransporteApp.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci', models.CharField(max_length=11)),
                ('sexo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_particular', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('anios_experiencia', models.IntegerField()),
                ('nivel_escolar', models.CharField(max_length=255)),
                ('salario_basico', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='TransporteApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='NominaSalario',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_dias', models.IntegerField()),
                ('salario', models.IntegerField()),
                ('mes', models.DateTimeField()),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransporteApp.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Moderno',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gasto_km', models.CharField(max_length=255)),
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TransporteApp.camion')),
            ],
        ),
        migrations.AddField(
            model_name='chofer',
            name='trabajador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TransporteApp.trabajador'),
        ),
        migrations.CreateModel(
            name='Antiguo',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio_fabricacion', models.IntegerField()),
                ('cantidad_reparaciones', models.IntegerField()),
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TransporteApp.camion')),
            ],
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.CharField(max_length=255)),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TransporteApp.trabajador')),
            ],
        ),
    ]
